// <auto-generated />
namespace SalinoMvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asas));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291739164_asas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
